### ISSUE TITLE
1.0!

### ISSUE THREAD

**Issue by remotevase** [TesseractTeam/WingProxy#5]
PLZ UPDATE!

**Comment by remotevase** [comment]
Yay! @xZeroMCPE You awesome!

**Comment by remotevase** [comment]
BUMP!

**Comment by remotevase** [comment]
I'm bumping again: Now that the other prooblem is fixed, can we update this please?!

**Comment by kaliiksPro** [comment]
Why it block me for 5 sec.?

**Comment by remotevase** [comment]
THis project is mostly left behind. Abandonned.
